version: '3.9'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: contacts-api
    restart: unless-stopped
    env_file: .env
    ports:
      - '3000:3000'
    networks:
      - app-network
  db:
    image: mongo
    container_name: db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
